### ISSUE TITLE
List of features to be ported over from Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#177]
### Descriptive summary

This issue will serve as a single place to track all of the features currently in Scholar that need to be ported over to UCrate.  Add additional items as needed.

## Works  
- [x] Use new work page instead of modal #249
- [x] Work types #197 + #219 + #220 + #226
- [x] Remove TODO in multiple work type #232
#### Create/Edit page
- [x] Allow work creation without attached files #209
- [x] Auto-populate the creator field when creating a work #210 
- [x] Visibility text #251
- [x] Hide admin set controls #261
- [x] default new works to public visibility #250 
- [x] Help flash message on dataset work types #259 
- [x] Hide group sharing on the Share tab for work edit page #260
- [x] license wizard #235 
- [x] Add suggestions to top of new work forms #289
- [x] DOIs #330
#### Show page
- [x] display permalinks (works and files show pages) #207

## Search
- [x] Add `Browse` button alongside search box #247
- [x] Boost collection ranking in search #208
- [x] Nav bar links (People About Contact Help) #257
- [x] Configure /catalog search results page to display same fields as Scholar #246
- [x] Configure facets to display the same as Scholar #245

## Users
- [x] ORCID integration #179 
- [x] new user welcome page/email #174
- [x] user profile fields #172 + #188
- [x] people page #129 + #181
- [x] Some user profile fields should be read-only #301

## Branding
- [x] Replicate Scholar's red links and buttons #274
- [x] Replicate Scholar's home page "jumbotron" #275
- [x] Replicate Scholar's navbar header #273 
- [x] Replicate Scholar's footer #412

## Misc
- [x] sitemap.xml #180
- [x] Rake task to notify and release embargoes #200 
- [x] static/help pages #199 
- [x] ETD manager role #248
- [x] Preserve line breaks on show pages for multi-line fields #267 
- [x] Update content on static pages to match Scholar #288 
- [x] Change the embargo_manager:notify task to run 1 day prior to expiration #287
- [x] Fix sitemap links for collections #286
- [x] Welcome page errors when user is not logged in #283
- [x] Replicate Scholar's home page content #276
- [x] Port over Adobe Reader link from Scholar #282
- [x] Port over the manifest generator from Scholar #303
- [x] featured items (work, researcher, collection) #182 + #293 + #294 + #295
- [x] Restore Dashboard, Works, and Collections links to the masthead #307
- [x] Modify the user drop-down menu #308
- [x] Stop using the "dashboard" version of the user profile page #309
- [x] Notification mailer #264 
- [x] Modify batch upload to behave the same as in Scholar #304
- [x] Modify batch edit to behave the same as in Scholar #305
- [x] Make sure proxy functionality behaves the same as Scholar #203
- [x] Port over the batch uploader task from Scholar #306
- [x] Title sort on the catalog index page #333 
- [x] Statistics gathering #413
- [x] Port over remaining scripts from https://github.com/uclibs/scholar_uc/tree/develop/script (part of #381)
