### ISSUE TITLE
Implement a REST API interface that allows work creation

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#750]
### Descriptive summary

Refs: #707

We need a (versioned) API for integration with Research Directory and other services.  The API should allow us to send JSON to Scholar to create and update works.

The API should allow remote services to use an API key to create content (instead of passing user authentication)

### Resources:
* Original issue on scholar_uc_legacy: https://github.com/uclibs/scholar_uc_legacy/issues/19
* API Documentation : https://systest.ahctest.uc.edu/eprof/cfc/fetcheprofdatadoc.cfc?method=getdocumentation
* Example of API return on a 6+2 query: https://git.uc.edu/UCLIBS/api-documentation/blob/master/research_directory/get_wb_page_data-sample-formatted.xml

### Sample JSON responses for Scholar searches, collections, works, and files:
* https://scholar.uc.edu/catalog.json
* https://scholar.uc.edu/collections/h128nf812.json
* https://scholar.uc.edu/concern/images/kw52j9012.json
* https://scholar.uc.edu/concern/parent/kw52j9012/file_sets/cn69m5141.json

### Other Samvera implementations using APIs for ingest
* https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Ingest+API
* https://github.com/aic-collections/aicdams-lakeshore/blob/master/script/ingest-api.sh

### Minimal set of components for ingesting a file into Scholar
* UC login (and an established user object in Rails database)
* Select a work type
* Metadata
    * Title
    * Creator (multiple)
    * College
    * Program/Department
    * Description
    * License
    * Advisor (multiple) - Student Works, ETDs
    * Degree Program - ETDs
* Select visibility
* Read and agree to distribution license
* Upload file

### Tasks
- [x] Collections: create, update, read
- [x] Works: create, update, read
- [x] Users: create, update, read
- [x] File upload, attach, characterize
- [x] API keys
- [x] Validation
- [x] API versioning
- [x] Documentation
- [x] Testing file upload in bulk
